package com.elevateiq.backend.seeder;

import com.elevateiq.backend.models.Course;
import com.elevateiq.backend.models.StudentActivity;
import com.elevateiq.backend.models.StudentCourseProgress;
import com.elevateiq.backend.models.UpcomingClass;
import com.elevateiq.backend.repository.CourseRepository;
import com.elevateiq.backend.repository.StudentActivityRepository;
import com.elevateiq.backend.repository.StudentCourseProgressRepository;
import com.elevateiq.backend.repository.UpcomingClassRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public class DataSeeder implements CommandLineRunner {

    @Autowired
    CourseRepository courseRepository;

    @Autowired
    UpcomingClassRepository upcomingClassRepository;

    @Autowired
    StudentActivityRepository activityRepository;

    @Autowired
    StudentCourseProgressRepository progressRepository;

    @Override
    public void run(String... args) throws Exception {
        seedCourses();
        // Since we don't know the exact studentId for the newly registered users (it's dynamically generated by Mongo),
        // we will create some dummy data linked to a generic 'student' user if possible, or wait for them to be fetched dynamically.
        // Actually, to make the student dashboard look alive immediately, we can seed data without a strict foreign key check,
        // but it won't show up unless we know the student ID. 
        // We'll skip seeding specific student data here since it requires a hardcoded studentId, but we seeded Courses!
    }

    private void seedCourses() {
        if (courseRepository.count() == 0) {
            Course c1 = new Course(
                "Full Stack Web Development",
                "Development",
                499.0,
                999.0,
                "6 Months",
                4.9,
                12450,
                "/images/courses/web-dev.jpg",
                List.of("React & Node.js", "10+ Projects", "Placement Support"),
                "Master modern full-stack development with React, Node.js, Express, and MongoDB. Build real-world applications and deploy them to the cloud.",
                List.of(
                    new Course.CourseModule(1, "Frontend Fundamentals", "4 Weeks"),
                    new Course.CourseModule(2, "Advanced React", "6 Weeks"),
                    new Course.CourseModule(3, "Backend with Node.js", "6 Weeks")
                )
            );

            Course c2 = new Course(
                "Data Science & Machine Learning",
                "Data Science",
                599.0,
                1199.0,
                "8 Months",
                4.8,
                8230,
                "/images/courses/data-science.jpg",
                List.of("Python & R", "Real Datasets", "AI Integration"),
                "Learn data analysis, visualization, and machine learning algorithms. Build predictive models using Python, scikit-learn, and TensorFlow.",
                List.of(
                    new Course.CourseModule(1, "Python for Data Science", "4 Weeks"),
                    new Course.CourseModule(2, "Data Analysis & Visualization", "4 Weeks"),
                    new Course.CourseModule(3, "Machine Learning Basics", "6 Weeks")
                )
            );

            Course c3 = new Course(
                "Cloud Computing with AWS",
                "Cloud",
                399.0,
                799.0,
                "4 Months",
                4.7,
                5120,
                "/images/courses/cloud.jpg",
                List.of("AWS Certification", "DevOps Tools", "Live Labs"),
                "Prepare for AWS certifications while learning essential cloud architecture patterns, security best practices, and DevOps methodologies.",
                List.of(
                    new Course.CourseModule(1, "Cloud Fundamentals", "2 Weeks"),
                    new Course.CourseModule(2, "Core AWS Services", "6 Weeks"),
                    new Course.CourseModule(3, "Architecture & Security", "4 Weeks")
                )
            );

            courseRepository.saveAll(List.of(c1, c2, c3));
            System.out.println("✅ Seeded Courses Collection!");
        } else {
            System.out.println("⚡ Courses collection already populated. Skipping seeder.");
        }
    }
}
