spring.application.name=backend
server.port=8080

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://bhargav_mongo:123450@cluster0.r3gcqp7.mongodb.net/elevateiq_db?retryWrites=true&w=majority

# JWT Secret (In production, this should be an environment variable)
jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
jwt.expirationMs=86400000
